### PR TITLE
[No-JIRA] BpkText.getFont() available from java

### PR DESCRIPTION
**Pull request by amolgupta**
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/master/CONTRIBUTING.md)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by tiagoengel** [comment]
Can you add the unreleased entry please?

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:

`com.github.Skyscanner:backpack-android:3de01391beb278dfc043c3d2b8ed6da8c200cea3`

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:

`com.github.Skyscanner:backpack-android:84c343b72db2be5a26f252935ca1996b69a7ef77`

**Comment by tiagoengel** [comment]
closed in favour of #274

**Pull request closed without merging**
