### PR TITLE
OGM-512 Implement whole month calendar selection

### PR DESCRIPTION
**Pull request by ernestkamara**
+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)

Remember to include the following changes:
+ [x] Component `README.md`
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GUIDELINES.md)

### CODE REVIEW

**Comment by sergiomarqmoura** [comment]
Looking into the [design specs](https://www.figma.com/file/i6ITHORdh1X07sTZjpytko/Combined-Search---Shopfront?node-id=3697%3A13207), it seems like only the first work should be capitalised and we're capitalising every word. Did we agree on this with them?

**Comment by ernestkamara** [comment]
> Looking into the [design specs](https://www.figma.com/file/i6ITHORdh1X07sTZjpytko/Combined-Search---Shopfront?node-id=3697%3A13207), it seems like only the first work should be capitalised and we're capitalising every word. Did we agree on this with them?



> Looking into the [design specs](https://www.figma.com/file/i6ITHORdh1X07sTZjpytko/Combined-Search---Shopfront?node-id=3697%3A13207), it seems like only the first work should be capitalised and we're capitalising every word. Did we agree on this with them?

@sergiomarqmoura Thanks for spotting this. It's a minor issue since this string would be added from the consumer of the Calender. But I will update the screenshot for consistency.

**Comment by sergiomarqmoura** [comment]
> > Looking into the [design specs](https://www.figma.com/file/i6ITHORdh1X07sTZjpytko/Combined-Search---Shopfront?node-id=3697%3A13207), it seems like only the first work should be capitalised and we're capitalising every word. Did we agree on this with them?
> 
> > Looking into the [design specs](https://www.figma.com/file/i6ITHORdh1X07sTZjpytko/Combined-Search---Shopfront?node-id=3697%3A13207), it seems like only the first work should be capitalised and we're capitalising every word. Did we agree on this with them?
> 
> @sergiomarqmoura Thanks for spotting this. It's a minor issue since this string would be added from the consumer of the Calender. But I will update the screenshot for consistency.

Ahh perfect, that's great @ernestkamara

**Comment by ernestkamara** [comment]
Closing this since it has been replaced with #1064

**Pull request closed without merging**
