### PR TITLE
no-jira travis notifications

### PR DESCRIPTION
**Pull request by amolgupta**
Experrimental PR. Do not merge.

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/master/CONTRIBUTING.md)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by amolgupta** [comment]
comment

**Comment by georgegillams** [comment]
comment

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:
`com.github.221:backpack-android:master`

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:

`com.github.Skyscanner:backpack-android:aa437059172dae394123d51e73e4f54fdfddff03`

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:

`com.github.Skyscanner:backpack-android:aa437059172dae394123d51e73e4f54fdfddff03`

**Comment by georgegillams** [comment]
Thank you for your contribution.
You can use the following dependency to test your application while we review your pull request:

`com.github.Skyscanner:backpack-android:f4ad88ca8c05372b68fc0058c6d00fed841ae766`

**Pull request merged**
